services:
  api:
    build:
      context: .
      dockerfile: backend_api/Dockerfile
    container_name: coupon_api_prod
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./media_data:/app/media

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: coupon_worker_prod
    restart: always
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1

  reward_worker:
    build:
      context: .
      dockerfile: Dockerfile.reward_worker
    container_name: coupon_reward_worker_prod
    restart: always
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1

  stats_worker:
    build:
      context: .
      dockerfile: Dockerfile.stats_worker
    container_name: coupon_stats_worker_prod
    restart: always
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
  # Frontends are deployed to Vercel
