"""Add cascade delete to event relations

Revision ID: 26d32e460e81
Revises: 98988c481416
Create Date: 2026-01-18 14:12:57.728959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d32e460e81'
down_revision: Union[str, None] = '98988c481416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_constraint('coupons_event_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_constraint('event_participants_event_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('event_participants_event_id_fkey', 'events', ['event_id'], ['id'])

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('coupons_event_id_fkey', 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###
