"""add_slug_to_events

Revision ID: 38ace7e3f8c6
Revises: df2d1d865096
Create Date: 2026-01-19 10:25:41.716583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ace7e3f8c6'
down_revision: Union[str, None] = 'df2d1d865096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add column as nullable first
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=50), nullable=True))
    
    # 2. Populate existing rows
    # Pure SQL execution for portability and speed
    op.execute("UPDATE events SET slug = 'event-' || id WHERE slug IS NULL")
    
    # 3. Alter column to be nullable=False and add index
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('slug', nullable=False)
        batch_op.create_index(batch_op.f('ix_events_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
