"""create_worker_logs

Revision ID: 4abd1ec0183f
Revises: bf4a49d98625
Create Date: 2026-01-18 16:53:57.887770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4abd1ec0183f'
down_revision: Union[str, None] = 'bf4a49d98625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
