"""initial_schema

Revision ID: 4b108025c3c5
Revises: 
Create Date: 2026-01-25 13:12:24.535895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b108025c3c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('verification_code', sa.String(), nullable=True),
    sa.Column('verification_code_expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_users_username'), ['username'], unique=True)

    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('total_points', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_participants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participants_username'), ['username'], unique=False)

    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_configs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_configs_key'), ['key'], unique=True)

    op.create_table('worker_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=True),
    sa.Column('saved_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worker_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_logs_id'), ['id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('won_point_multiplier', sa.Float(), nullable=False),
    sa.Column('loss_point_multiplier', sa.Float(), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_events_status'), ['status'], unique=False)

    op.create_table('magic_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('magic_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_magic_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_magic_tokens_token'), ['token'], unique=True)

    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('bet_id', sa.String(length=64), nullable=False),
    sa.Column('bet_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('combination_count', sa.Integer(), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=True),
    sa.Column('overall_state', sa.String(length=16), nullable=True),
    sa.Column('winning', sa.Float(), nullable=True),
    sa.Column('calculation', sa.Float(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('inserted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupons_bet_id'), ['bet_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_coupons_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupons_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupons_id'), ['id'], unique=False)

    op.create_table('event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('total_points', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'participant_id', name='uq_event_participant')
    )
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_participants_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_participants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_participants_participant_id'), ['participant_id'], unique=False)

    op.create_table('coupon_event_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.Column('eligibility_reason', sa.Text(), nullable=True),
    sa.Column('coupon_state', sa.String(length=16), nullable=True),
    sa.Column('points_earned', sa.Float(), nullable=False),
    sa.Column('points_calculation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coupon_id', 'event_id', name='uq_coupon_event')
    )
    with op.batch_alter_table('coupon_event_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupon_event_results_coupon_id'), ['coupon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_event_results_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_event_results_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon_event_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupon_event_results_id'))
        batch_op.drop_index(batch_op.f('ix_coupon_event_results_event_id'))
        batch_op.drop_index(batch_op.f('ix_coupon_event_results_coupon_id'))

    op.drop_table('coupon_event_results')
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_participants_participant_id'))
        batch_op.drop_index(batch_op.f('ix_event_participants_id'))
        batch_op.drop_index(batch_op.f('ix_event_participants_event_id'))

    op.drop_table('event_participants')
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupons_id'))
        batch_op.drop_index(batch_op.f('ix_coupons_event_id'))
        batch_op.drop_index(batch_op.f('ix_coupons_client_id'))
        batch_op.drop_index(batch_op.f('ix_coupons_bet_id'))

    op.drop_table('coupons')
    with op.batch_alter_table('magic_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_magic_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_magic_tokens_id'))

    op.drop_table('magic_tokens')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_status'))
        batch_op.drop_index(batch_op.f('ix_events_slug'))
        batch_op.drop_index(batch_op.f('ix_events_id'))

    op.drop_table('events')
    with op.batch_alter_table('worker_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_logs_id'))

    op.drop_table('worker_logs')
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_configs_key'))
        batch_op.drop_index(batch_op.f('ix_system_configs_id'))

    op.drop_table('system_configs')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_username'))
        batch_op.drop_index(batch_op.f('ix_participants_id'))
        batch_op.drop_index(batch_op.f('ix_participants_client_id'))

    op.drop_table('participants')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_username'))
        batch_op.drop_index(batch_op.f('ix_admin_users_id'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
