"""Add EventParticipant table

Revision ID: 98988c481416
Revises: add_event_id_002
Create Date: 2026-01-18 15:35:50.835064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98988c481416'
down_revision: Union[str, None] = 'add_event_id_002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'participant_id', name='uq_event_participant')
    )
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_participants_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_participants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_participants_participant_id'), ['participant_id'], unique=False)

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.alter_column('overall_state',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               type_=sa.String(length=16),
               existing_nullable=True)
        batch_op.alter_column('is_processed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_coupons_event_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'])

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('total_points',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
        batch_op.alter_column('joined_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_participants_username'))
        batch_op.create_index(batch_op.f('ix_participants_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_username'))
        batch_op.create_index(batch_op.f('ix_participants_username'), ['username'], unique=True)
        batch_op.alter_column('joined_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
        batch_op.alter_column('total_points',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=True)
        batch_op.alter_column('client_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_coupons_event_id'), 'events', ['event_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('is_processed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
        batch_op.alter_column('overall_state',
               existing_type=sa.String(length=16),
               server_default=sa.text("'Pending'::character varying"),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_participants_participant_id'))
        batch_op.drop_index(batch_op.f('ix_event_participants_id'))
        batch_op.drop_index(batch_op.f('ix_event_participants_event_id'))

    op.drop_table('event_participants')
    # ### end Alembic commands ###
