"""Change calculation to Float

Revision ID: bf4a49d98625
Revises: 26d32e460e81
Create Date: 2026-01-18 14:51:45.465478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4a49d98625'
down_revision: Union[str, None] = '26d32e460e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.alter_column('calculation',
               existing_type=sa.BOOLEAN(),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using="CASE WHEN calculation THEN 1.0 ELSE 0.0 END")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.alter_column('calculation',
               existing_type=sa.Float(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
