"""create_worker_logs_table

Revision ID: df2d1d865096
Revises: d76bf45fd374
Create Date: 2026-01-19 07:58:43.182170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df2d1d865096'
down_revision: Union[str, None] = 'd76bf45fd374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=True),
    sa.Column('saved_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worker_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_logs_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_logs_id'))

    op.drop_table('worker_logs')
    # ### end Alembic commands ###
